dependencies:
 - python=3.7
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - requests
 - pandas
 - seaborn
 - openpyxl
 - os
 - json
 - pprint
 - copy
 - tqdm
 - shutil
 - gzip
 - pip:
   - watermark
   - pytest